// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbCtxUEVn8npe4pe5Zmnh05lx8tVhClv4',
    appId: '1:365767152501:web:1a395f5a56cc0d6ffff93c',
    messagingSenderId: '365767152501',
    projectId: 'athar-app-384b5',
    authDomain: 'athar-app-384b5.firebaseapp.com',
    storageBucket: 'athar-app-384b5.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCiQXM1aejBoZANv1IVr9FkJti-FyRwPHI',
    appId: '1:365767152501:android:71ef01eebd93b6e8fff93c',
    messagingSenderId: '365767152501',
    projectId: 'athar-app-384b5',
    storageBucket: 'athar-app-384b5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZmD_k0xnhlX8x0wAAz0_CboRw0gujDTI',
    appId: '1:365767152501:ios:37c6385762378b9bfff93c',
    messagingSenderId: '365767152501',
    projectId: 'athar-app-384b5',
    storageBucket: 'athar-app-384b5.firebasestorage.app',
    iosBundleId: 'com.athar.athar',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZmD_k0xnhlX8x0wAAz0_CboRw0gujDTI',
    appId: '1:365767152501:ios:37c6385762378b9bfff93c',
    messagingSenderId: '365767152501',
    projectId: 'athar-app-384b5',
    storageBucket: 'athar-app-384b5.firebasestorage.app',
    iosBundleId: 'com.athar.athar',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDbCtxUEVn8npe4pe5Zmnh05lx8tVhClv4',
    appId: '1:365767152501:web:ea5a8fb711694036fff93c',
    messagingSenderId: '365767152501',
    projectId: 'athar-app-384b5',
    authDomain: 'athar-app-384b5.firebaseapp.com',
    storageBucket: 'athar-app-384b5.firebasestorage.app',
  );
}
